[package]
name = "gsc-client"
version = "0.1.0"
authors = ["Jesse A. Tov <jesse@eecs.northwestern.edu>"]
edition = "2018"

[dependencies]
#env_logger = "0.5.13"
error-chain = "0.12.0"
#log = "0.4.5"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8.3"
reqwest = "0.8.8"
rpassword = "2.0"
vlog = "0.1.4"
