[package]
name = "gsc-client"
version = "0.1.0"
authors = ["Jesse A. Tov <jesse@eecs.northwestern.edu>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = "2.0.32"
error-chain = "0.12.0"
globset = "0.4.2"
lazy_static = "1.1"
regex = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8.3"
reqwest = "0.8.8"
rpassword = "2.0"
vlog = "0.1.4"
